---

- name: Get InfluxDB APT GPG key
  apt_key:
    url: 'https://repos.influxdata.com/influxdb.key '
    id: '{{ influxdb_apt_repo_key_fingerprint }}'
    state: present

- name: Configure InfluxDB APT repository
  apt_repository:
    repo: 'deb {{ influxdb_apt_repo_base }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    state: present
    update_cache: True            

- name: Check if InfluxDB is already installed
  stat:
    path: '/etc/influxdb/influxdb.conf'
  register: influxdb_server_register_influxdb_exists

- name: Ensure influxdb packages are installed
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ influxdb_packages_base }}'
    - '{{ influxdb_packages }}'
    - '{{ influxdb_server_protocol_collectd_packages[influxdb_server_protocol_collectd_enabled] }}'
  tags: [ 'role::influxdb:base_install' ]

- name: Make sure that Ansible local fact directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save InfluxDB local facts
  template:
    src: 'etc/ansible/facts.d/influxdb.fact.j2'
    dest: '/etc/ansible/facts.d/influxdb.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: influxdb_server_register_local_facts
  tags: [ 'role::postgresql_server:config' ]

- name: Re-read local facts if they have been changed
  action: setup
  when: influxdb_server_register_local_facts|d() and
        influxdb_server_register_local_facts.changed
  tags: [ 'role::influxdb_server:config' ]

- name: Add influxdb user to ssl-cert system group 
  user:
    name: 'influxdb'
    state: 'present'
    createhome: False
    groups: 'ssl-cert'
    append: True

- name: Ensure InfluxDB is running
  service:
    name: 'influxdb'
    state: 'started'

- name: Wait for InfluxDB to start on the first install
  wait_for:
    port: 8086
    timeout: 60
  when: (not influxdb_server_register_influxdb_exists.stat.exists)

- name: Create admin user on the first install
  shell: /usr/bin/influx -execute "CREATE USER {{ influxdb_server_admin_user }} WITH PASSWORD '{{ influxdb_server_admin_password }}' WITH ALL PRIVILEGES"
  when: (not influxdb_server_register_influxdb_exists.stat.exists)
  no_log: True

- name: Divert original /etc/influxdb/influxdb.conf
  command: dpkg-divert --quiet --local --divert /etc/influxdb/influxdb.conf.dpkg-divert --rename /etc/influxdb/influxdb.conf
  args:
    creates: '/etc/influxdb/influxdb.conf.dpkg-divert'

- name: Install config file
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - 'etc/influxdb/influxdb.conf'
  notify: [ 'Restart InfluxDB' ]
